Fix error on build using Python 3.9
$ ./dev release
Traceback (most recent call last):
  File "/home/mscastanho/src/cpi-breakdown/./setup.py", line 37, in <module>
    REQUIREMENTS = [str(required.req) for required in REQUIREMENTS_LIST]
  File "/home/mscastanho/src/cpi-breakdown/./setup.py", line 37, in <listcomp>
    REQUIREMENTS = [str(required.req) for required in REQUIREMENTS_LIST]
AttributeError: 'ParsedRequirement' object has no attribute 'req'
Traceback (most recent call last):
  File "/home/mscastanho/src/cpi-breakdown/./setup.py", line 37, in <module>
    REQUIREMENTS = [str(required.req) for required in REQUIREMENTS_LIST]
  File "/home/mscastanho/src/cpi-breakdown/./setup.py", line 37, in <listcomp>
    REQUIREMENTS = [str(required.req) for required in REQUIREMENTS_LIST]
AttributeError: 'ParsedRequirement' object has no attribute 'req'

Looks like the name of 'req' argument in ParsedRequirement changed to
'requirement'. Let's accept both options so all versions work.